# Select image from https://hub.docker.com/r/movoin/devops-swoole/
image: movoin/devops-swoole:2

# Run PHPUnit
phpunit:
  before_script:
    - composer install
    - pecl install xdebug
    - echo 'zend_extension=xdebug.so' > /etc/php/conf.d/xdebug.ini
    - chown -R app:app /builds/onelab/one.swoole
  script:
    - su - app "/usr/local/bin/php /builds/onelab/one.swoole/vendor/bin/phpcs -p --standard=PSR2 --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 src"
    - su - app "/usr/local/bin/php /builds/onelab/one.swoole/vendor/bin/parallel-lint . --exclude vendor"
    - su - app "/usr/local/bin/php /builds/onelab/one.swoole/vendor/bin/phpunit -c phpunit-ci.xml"
