# Select image from https://hub.docker.com/r/movoin/devops-swoole/
image: movoin/devops-swoole:2

before_script:
- composer install
- pecl install xdebug
- echo 'zend_extension=xdebug.so' > /etc/php/conf.d/xdebug.ini

# Run PHPUnit
phpunit:
  script:
  - vendor/bin/phpunit -c phpunit-ci.xml tests
